<?php

namespace Proxies\__CG__\Pnv\SaisieBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Activite extends \Pnv\SaisieBundle\Entity\Activite implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Pnv\\SaisieBundle\\Entity\\Activite' . "\0" . 'idActivite', '' . "\0" . 'Pnv\\SaisieBundle\\Entity\\Activite' . "\0" . 'annee', '' . "\0" . 'Pnv\\SaisieBundle\\Entity\\Activite' . "\0" . 'commentaire', '' . "\0" . 'Pnv\\SaisieBundle\\Entity\\Activite' . "\0" . 'dateCreation', '' . "\0" . 'Pnv\\SaisieBundle\\Entity\\Activite' . "\0" . 'dateModif', '' . "\0" . 'Pnv\\SaisieBundle\\Entity\\Activite' . "\0" . 'idAction', '' . "\0" . 'Pnv\\SaisieBundle\\Entity\\Activite' . "\0" . 'idActiviteTransv', '' . "\0" . 'Pnv\\SaisieBundle\\Entity\\Activite' . "\0" . 'idAgent', '' . "\0" . 'Pnv\\SaisieBundle\\Entity\\Activite' . "\0" . 'idDuree', '' . "\0" . 'Pnv\\SaisieBundle\\Entity\\Activite' . "\0" . 'idCommune', '' . "\0" . 'Pnv\\SaisieBundle\\Entity\\Activite' . "\0" . 'idJour', '' . "\0" . 'Pnv\\SaisieBundle\\Entity\\Activite' . "\0" . 'idMaitrise', '' . "\0" . 'Pnv\\SaisieBundle\\Entity\\Activite' . "\0" . 'idSemaine', '' . "\0" . 'Pnv\\SaisieBundle\\Entity\\Activite' . "\0" . 'idTerritoire');
        }

        return array('__isInitialized__', '' . "\0" . 'Pnv\\SaisieBundle\\Entity\\Activite' . "\0" . 'idActivite', '' . "\0" . 'Pnv\\SaisieBundle\\Entity\\Activite' . "\0" . 'annee', '' . "\0" . 'Pnv\\SaisieBundle\\Entity\\Activite' . "\0" . 'commentaire', '' . "\0" . 'Pnv\\SaisieBundle\\Entity\\Activite' . "\0" . 'dateCreation', '' . "\0" . 'Pnv\\SaisieBundle\\Entity\\Activite' . "\0" . 'dateModif', '' . "\0" . 'Pnv\\SaisieBundle\\Entity\\Activite' . "\0" . 'idAction', '' . "\0" . 'Pnv\\SaisieBundle\\Entity\\Activite' . "\0" . 'idActiviteTransv', '' . "\0" . 'Pnv\\SaisieBundle\\Entity\\Activite' . "\0" . 'idAgent', '' . "\0" . 'Pnv\\SaisieBundle\\Entity\\Activite' . "\0" . 'idDuree', '' . "\0" . 'Pnv\\SaisieBundle\\Entity\\Activite' . "\0" . 'idCommune', '' . "\0" . 'Pnv\\SaisieBundle\\Entity\\Activite' . "\0" . 'idJour', '' . "\0" . 'Pnv\\SaisieBundle\\Entity\\Activite' . "\0" . 'idMaitrise', '' . "\0" . 'Pnv\\SaisieBundle\\Entity\\Activite' . "\0" . 'idSemaine', '' . "\0" . 'Pnv\\SaisieBundle\\Entity\\Activite' . "\0" . 'idTerritoire');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Activite $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdActivite()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdActivite();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdActivite', array());

        return parent::getIdActivite();
    }

    /**
     * {@inheritDoc}
     */
    public function setAnnee($annee)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAnnee', array($annee));

        return parent::setAnnee($annee);
    }

    /**
     * {@inheritDoc}
     */
    public function getAnnee()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAnnee', array());

        return parent::getAnnee();
    }

    /**
     * {@inheritDoc}
     */
    public function setCommentaire($commentaire)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCommentaire', array($commentaire));

        return parent::setCommentaire($commentaire);
    }

    /**
     * {@inheritDoc}
     */
    public function getCommentaire()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCommentaire', array());

        return parent::getCommentaire();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateCreation($dateCreation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateCreation', array($dateCreation));

        return parent::setDateCreation($dateCreation);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateCreation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateCreation', array());

        return parent::getDateCreation();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateModif($dateModif)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateModif', array($dateModif));

        return parent::setDateModif($dateModif);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateModif()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateModif', array());

        return parent::getDateModif();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdAction(\Pnv\SaisieBundle\Entity\DicoAction $idAction = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdAction', array($idAction));

        return parent::setIdAction($idAction);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdAction()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdAction', array());

        return parent::getIdAction();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdActiviteTransv(\Pnv\SaisieBundle\Entity\DicoActiviteTransv $idActiviteTransv = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdActiviteTransv', array($idActiviteTransv));

        return parent::setIdActiviteTransv($idActiviteTransv);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdActiviteTransv()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdActiviteTransv', array());

        return parent::getIdActiviteTransv();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdAgent(\Pnv\SaisieBundle\Entity\DicoAgent $idAgent = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdAgent', array($idAgent));

        return parent::setIdAgent($idAgent);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdAgent()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdAgent', array());

        return parent::getIdAgent();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdDuree(\Pnv\SaisieBundle\Entity\DicoDuree $idDuree = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdDuree', array($idDuree));

        return parent::setIdDuree($idDuree);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdDuree()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdDuree', array());

        return parent::getIdDuree();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdCommune(\Pnv\SaisieBundle\Entity\DicoCommune $idCommune = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdCommune', array($idCommune));

        return parent::setIdCommune($idCommune);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdCommune()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdCommune', array());

        return parent::getIdCommune();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdJour(\Pnv\SaisieBundle\Entity\DicoJour $idJour = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdJour', array($idJour));

        return parent::setIdJour($idJour);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdJour()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdJour', array());

        return parent::getIdJour();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdMaitrise(\Pnv\SaisieBundle\Entity\DicoMaitrise $idMaitrise = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdMaitrise', array($idMaitrise));

        return parent::setIdMaitrise($idMaitrise);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdMaitrise()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdMaitrise', array());

        return parent::getIdMaitrise();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdSemaine(\Pnv\SaisieBundle\Entity\DicoSemaine $idSemaine = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdSemaine', array($idSemaine));

        return parent::setIdSemaine($idSemaine);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdSemaine()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdSemaine', array());

        return parent::getIdSemaine();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdTerritoire(\Pnv\SaisieBundle\Entity\DicoTerritoire $idTerritoire = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdTerritoire', array($idTerritoire));

        return parent::setIdTerritoire($idTerritoire);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdTerritoire()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdTerritoire', array());

        return parent::getIdTerritoire();
    }

}
