<?php

namespace Proxies\__CG__\Pnv\SaisieBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class DicoDomaineActivite extends \Pnv\SaisieBundle\Entity\DicoDomaineActivite implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Pnv\\SaisieBundle\\Entity\\DicoDomaineActivite' . "\0" . 'idDomaineActi', '' . "\0" . 'Pnv\\SaisieBundle\\Entity\\DicoDomaineActivite' . "\0" . 'numDomaineActi', '' . "\0" . 'Pnv\\SaisieBundle\\Entity\\DicoDomaineActivite' . "\0" . 'acronDomaineActi', '' . "\0" . 'Pnv\\SaisieBundle\\Entity\\DicoDomaineActivite' . "\0" . 'libDomaineActi', '' . "\0" . 'Pnv\\SaisieBundle\\Entity\\DicoDomaineActivite' . "\0" . 'infoDomaineActi');
        }

        return array('__isInitialized__', '' . "\0" . 'Pnv\\SaisieBundle\\Entity\\DicoDomaineActivite' . "\0" . 'idDomaineActi', '' . "\0" . 'Pnv\\SaisieBundle\\Entity\\DicoDomaineActivite' . "\0" . 'numDomaineActi', '' . "\0" . 'Pnv\\SaisieBundle\\Entity\\DicoDomaineActivite' . "\0" . 'acronDomaineActi', '' . "\0" . 'Pnv\\SaisieBundle\\Entity\\DicoDomaineActivite' . "\0" . 'libDomaineActi', '' . "\0" . 'Pnv\\SaisieBundle\\Entity\\DicoDomaineActivite' . "\0" . 'infoDomaineActi');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (DicoDomaineActivite $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdDomaineActi()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdDomaineActi();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdDomaineActi', array());

        return parent::getIdDomaineActi();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumDomaineActi($numDomaineActi)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumDomaineActi', array($numDomaineActi));

        return parent::setNumDomaineActi($numDomaineActi);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumDomaineActi()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumDomaineActi', array());

        return parent::getNumDomaineActi();
    }

    /**
     * {@inheritDoc}
     */
    public function setAcronDomaineActi($acronDomaineActi)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAcronDomaineActi', array($acronDomaineActi));

        return parent::setAcronDomaineActi($acronDomaineActi);
    }

    /**
     * {@inheritDoc}
     */
    public function getAcronDomaineActi()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAcronDomaineActi', array());

        return parent::getAcronDomaineActi();
    }

    /**
     * {@inheritDoc}
     */
    public function setLibDomaineActi($libDomaineActi)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLibDomaineActi', array($libDomaineActi));

        return parent::setLibDomaineActi($libDomaineActi);
    }

    /**
     * {@inheritDoc}
     */
    public function getLibDomaineActi()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLibDomaineActi', array());

        return parent::getLibDomaineActi();
    }

    /**
     * {@inheritDoc}
     */
    public function setInfoDomaineActi($infoDomaineActi)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInfoDomaineActi', array($infoDomaineActi));

        return parent::setInfoDomaineActi($infoDomaineActi);
    }

    /**
     * {@inheritDoc}
     */
    public function getInfoDomaineActi()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInfoDomaineActi', array());

        return parent::getInfoDomaineActi();
    }

}
